### ISSUE TITLE
Error with tolerance in test.

### ISSUE THREAD

**Issue by julianmateu** [julianmateu/Quaternion#2]
@basicNew, I have a failure in one of the tests, here is the message:

```
There was 1 failure:
1) testMultiplicationQuaternion(TestQuaternion)junit.framework.AssertionFailedError: expected:<( 1.0714285714285714 ; 0.0 ; 0.0 ; 2.7755575615628914E-17 )> but was:<( 1.0 ; 0.0 ; 0.0 ; 0.0 )>
    at TestQuaternion.testMultiplicationQuaternion(TestQuaternion.java:156)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 5,  Failures: 1,  Errors: 0
```

I suspect it is a tolerance issue. I can't define a tolerance for `assertEquals()` because it should be a double (there is no `assertEquals(Object,Object,Object)`, instead there is an `assertEquals(Object,Object,Object)`). I could define an `assertEquals` that subtracts the two objects an checks its difference is smaller than the tolerance, but the first number I get should be 1 and is 1.07. This seems a very big numerical error.

Here is the code of the method:

``` java
/**
  * Method to multiply two Quaternions and find their Hamilton product.
  *
  * @return Returns a new Quaternion with the result of the Hamilton product.
  */
public Quaternion multiply(Quaternion factor) {
  return new Quaternion(
    this.r * factor.getR() - this.i * factor.getI()
      - this.j * factor.getJ() - this.k * factor.getK(),
    this.r * factor.getI() + this.i * factor.getR()
      + this.j * factor.getK() - this.k * factor.getJ(),
    this.r * factor.getJ() - this.i * factor.getK()
      + this.j * factor.getR() + this.k * factor.getI(),
    this.r * factor.getK() + this.i * factor.getJ()
      - this.j * factor.getI() + this.k * factor.getR());
}
```

And here the code of the test:

``` java
assertEquals(new Quaternion(1, 2, 3, 4).multiply(new Quaternion(
                        ((double)1.0)/28, ((double)-2.0)/28, ((double)-3.0)/28, ((double)-4.0)/28)),
                new Quaternion(1, 0, 0, 0)); // Multiplying by right inverse.
```

**Comment by basicNew** [comment]
Couple of thoughts:
1. The `2.7755575615628914E-17` vs `0.0` looks like an expected rounding error. Comparing floats is a hard thing, as IEEE floating point arithmetic can't represent the whole Real space (see e.g. https://docs.python.org/2/tutorial/floatingpoint.html). To cope with this testing frameworks have a way to assert equality in a given delta (see e.g. http://stackoverflow.com/questions/7554281/junit-assertions-make-the-assertion-between-floats)
2. The `1.0714285714285714` vs `1.0` does seem suspicious. Are you sure there is no coding error?
3. getters and setters are also good to isolate your class implementation from itself, so you could change `this.r` for `this.getR()`

**Comment by julianmateu** [comment]
```
assertEquals(new Quaternion(1, 2, 3, 4).multiply(new Quaternion(
                        ((double)1.0)/28, ((double)-2.0)/28, ((double)-3.0)/28, ((double)-4.0)/28)),
                new Quaternion(1, 0, 0, 0)); // Multiplying by right inverse.
```

The problem with the `1.0714285714285714` vs `1.0` was because the norm of the quaternion was 30, not 28.

 The `2.7755575615628914E-17` vs `0.0` was a rounding error problem, so I created a new assert with a tolerance, comparing each component of the two quaternions with an `assertEquals`.

**Comment by basicNew** [comment]
:+1:
